# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-31 23:08
from __future__ import unicode_literals

from django.db import migrations
import workoutcal.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workoutcal', '0002_auto_20171231_2155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='cardio',
        ),
        migrations.AddField(
            model_name='workout',
            name='cardios',
            field=workoutcal.fields.CardiosField(null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='lifts',
            field=workoutcal.fields.LiftsField(null=True),
        ),
    ]
