# Generated by Django 2.0.1 on 2018-01-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutcal', '0005_auto_20180113_1641'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
